---

name: Python

"on":
  pull_request:
    branches:
      - develop
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    container: python:${{ matrix.python-version }}-alpine
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint with black
        run: |
          command -v black 1>/dev/null || pip install black
          black --check .

      - name: Lint with flake8
        run: |
          command -v flake8 1>/dev/null || pip install flake8
          flake8 .

      - name: Lint with isort
        run: |
          command -v isort 1>/dev/null || pip install isort
          isort --check .

      - name: Type-check with mypy
        run: |
          command -v mypy 1>/dev/null || pip install mypy
          mypy algorithms/

      - name: Tests
        run: |
          command -v pipenv 1>/dev/null || apt install --no-install-recommends -y pipenv
          pipenv install --dev -e .
          pipenv run pytest
